language: node_js
node_js:
  - "9"
sudo: required

branches:
  only:
  - gh-pages

install:
  - npm i vuepress -g

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local-dir: .vuepress/dist
  keep-history: true
  target-branch: master
  on:
    branch: gh-pages
